In [1]:
import numpy as np
import pandas as pd

#Load the dataset

file_path = 'Advertising1.csv'
df = pd.read_csv(file_path)
df.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,27-03-2016 00:53,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,04-04-2016 01:39,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,13-03-2016 20:35,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,10-01-2016 02:31,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,03-06-2016 03:36,0

In [2]:
df.columns

Index(['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage', 'Ad Topic Line', 'City', 'Male', 'Country',
       'Timestamp', 'Clicked on Ad'],
      dtype='str')

In [3]:
df.describe()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Male,Clicked on Ad
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,65.000200,36.009000,55000.000080,180.000100,0.481000,0.50000
std,15.853615,8.785562,13414.634022,43.902339,0.499889,0.50025
min,32.600000,19.000000,13996.500000,104.780000,0.000000,0.00000
25%,51.360000,29.000000,47031.802500,138.830000,0.000000,0.00000
50%,68.215000,35.000000,57012.300000,183.130000,0.000000,0.50000
75%,78.547500,42.000000,65470.635000,218.792500,1.000000,1.00000
max,91.430000,61.000000,79484.800000,269.960000,1.000000,1.00000

In [4]:
basic_info = df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   str
 5   City                      1000 non-null   str
 6   Male                      1000 non-null   int64
 7   Country                   1000 non-null   str
 8   Timestamp                 1000 non-null   str
 9   Clicked on Ad             1000 non-null   int64
dtypes: float64(3), int64(3), str(4)
memory usage: 78.3 KB

In [5]:
#Holdout method

from sklearn.model_selection import train_test_split

X= df[['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage', 'Male']]

y= df['Clicked on Ad']        # Target (dependent variable)
                                # This is what we want to predict (0 = NO, 1 = YES)

                            # ---------------Train-Test-Split----------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size= 0.3,                     # 30% data for testing, 70% for training
    random_state= 42,             # Fixes randomness -> same split every time --> Fixes random split so output stays same every run
    stratify = y                 # keeps same class proportion in both train and test --> Maintains same class ratio in train and test
)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((700, 5), (300, 5), (700,), (300,))

In [6]:
#Straitified sampling -- cross validation
# (NOTE : actual stratification already happened during train_test_split)

In [7]:
# model training and evaluation using accuracy on training and test data

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

log_reg = LogisticRegression(max_iter = 1000)
log_reg.fit(X_train, y_train)

y_train_pred = log_reg.predict(X_train)
y_test_pred = log_reg.predict(X_test)

train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print(f"Training Accuracy:", train_accuracy)
print(f"Testing Accuracy:", test_accuracy)

Training Accuracy: 0.9685714285714285
Testing Accuracy: 0.9766666666666667

In [8]:
# Shuffle Split Cross Validation using LogisticRegression

import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import ShuffleSplit, cross_validate

model = LogisticRegression(solver='liblinear')

#-------------------ShuffleSplitSetup-------------------------------------

Shuffle_split = ShuffleSplit(
    n_splits = 200,
    test_size = 0.3,
    random_state = 42
)

#Corss Validation

cv_results = cross_validate (
    model,X,y,
    cv = Shuffle_split,
    scoring ='accuracy',
    return_train_score = True
)

#------------------------Extract Scores----------------------------------

train_scores = cv_results['train_score']
test_scores = cv_results['test_score']

print("Cross Validation Train Accuracy:", np.round(train_scores.mean(), 2))
print("Cross Validation Test Accuracy:", np.round(test_scores.mean(), 2))

Cross Validation Train Accuracy: 0.9
Cross Validation Test Accuracy: 0.9

In [9]:
# K-Fold Cross Validate using Logistic Regression.

In [13]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='liblinear')

# K-Fold Setup

from sklearn.model_selection import KFold, cross_validate

kfold = KFold(
    n_splits = 5,
    shuffle = True,
    random_state = 42
)

# Cross Validate

cv_results = cross_validate(
    model , X, y,
    cv = kfold,
    scoring = 'accuracy',
    return_train_score = True
)

#-------------------EXTRACT SCORES--------------------------------------------------

train_scores = cv_results['train_score']

test_scores = cv_results['test_score']

print("Cross Validation : train accuracy:", np.round(train_scores.mean(), 2))

print("Cross Validation : test accuracy:", np.round(test_scores.mean(), 2))

Cross Validation : train accuracy: 0.9
Cross Validation : test accuracy: 0.9